language: node_js
node_js:
    - lts/*
script:
    - yarn add -D vuepress
    - yarn build
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: docs/.vuepress/dist
    github-token: $GITHUB_TOKEN
    on:
        branch: master
